var numNumbers = 4;
var numBottles = 1;
var num3 = -5.067;
var days = 365;
var myName = "Bret";
var location = "Coding Dojo";
var markerBrand = "expo";
var inChair = true;
var cupFilled = false;
var undef;
console.log("Number number 1: ", numNumbers);
console.log("Number number 2: ", numBottles);
console.log("Number number 3: ", num3);
console.log("Number number 4: ", days);
console.log("String number 1: ", myName);
console.log("String number 2: ", location);
console.log("String number 3: ", markerBrand);
console.log("Boolian number 1: ", inChair);
console.log("Boolian number 2: ", cupFilled);
console.log("Undefined variable:", undef);